services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd

  users-import:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./mongo/data/users.json:/src/data/users.json
    command: >
      mongoimport
      --host mongo
      --username root
      --password pwd
      --authenticationDatabase admin
      --db reactive_paradigm
      --collection users
      --file /src/data/users.json
      --jsonArray

  products-import:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./mongo/data/products.json:/src/data/products.json
    command: >
      mongoimport
      --host mongo
      --username root
      --password pwd
      --authenticationDatabase admin
      --db reactive_paradigm
      --collection products
      --file /src/data/products.json
      --jsonArray

  orders-import:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./mongo/data/orders.json:/src/data/orders.json
    command: >
      mongoimport
      --host mongo
      --username root
      --password pwd
      --authenticationDatabase admin
      --db reactive_paradigm
      --collection orders
      --file /src/data/orders.json
      --jsonArray


  order-search-service:
    build:
      context: ./order-search-service
      dockerfile: Dockerfile
    image: order-search-service
    ports:
      - 8081:8080

  product-info-service:
    build:
      context: ./product-info-service
      dockerfile: Dockerfile
    image: product-info-service
    ports:
      - 8082:8080

  main-user-be:
    build:
      context: ./main-user-be
      dockerfile: Dockerfile
    image: main-user-be
    ports:
      - 8083:8080